# Generated by Django 6.1.1 on 2026-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('room_type', models.CharField(choices=[('private', 'Отдельная комната'), ('shared', 'Совместная комната'), ('studio', 'Студия целиком')], default='private', max_length=20, verbose_name='Тип жилья')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц (₽)')),
                ('available_from', models.DateField(verbose_name='Доступно с')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
