# Generated by Django 6.1.1 on 2026-10-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Направление')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Регион / Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание направления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('tour_type', models.CharField(choices=[('trekking', 'Треккинг и походы'), ('jeep', 'Джип-тур'), ('sightseeing', 'Экскурсионный тур'), ('rafting', 'Сплав и водный тур'), ('photo', 'Фототур')], default='sightseeing', max_length=30, verbose_name='Тип тура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость тура (₽)')),
                ('duration_days', models.PositiveIntegerField(default=3, verbose_name='Длительность (дней)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('max_group_size', models.PositiveIntegerField(default=10, verbose_name='Макс. участников в группе')),
                ('description', models.TextField(blank=True, verbose_name='Программа тура')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.destination', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created_at'],
            },
        ),
    ]
